// Code generated by protoc-gen-go. DO NOT EDIT.
// source: src/person/person.v3.proto

/*
Package person is a generated protocol buffer package.

It is generated from these files:
	src/person/person.v3.proto

It has these top-level messages:
	Person
*/
package person

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Person struct {
	Name  *Person_Name    `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Email []*Person_Email `protobuf:"bytes,2,rep,name=email" json:"email,omitempty"`
}

func (m *Person) Reset()                    { *m = Person{} }
func (m *Person) String() string            { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()               {}
func (*Person) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Person) GetName() *Person_Name {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *Person) GetEmail() []*Person_Email {
	if m != nil {
		return m.Email
	}
	return nil
}

type Person_Name struct {
	Family   string `protobuf:"bytes,1,opt,name=family" json:"family,omitempty"`
	Personal string `protobuf:"bytes,2,opt,name=personal" json:"personal,omitempty"`
}

func (m *Person_Name) Reset()                    { *m = Person_Name{} }
func (m *Person_Name) String() string            { return proto.CompactTextString(m) }
func (*Person_Name) ProtoMessage()               {}
func (*Person_Name) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

func (m *Person_Name) GetFamily() string {
	if m != nil {
		return m.Family
	}
	return ""
}

func (m *Person_Name) GetPersonal() string {
	if m != nil {
		return m.Personal
	}
	return ""
}

type Person_Email struct {
	Kind    string `protobuf:"bytes,1,opt,name=kind" json:"kind,omitempty"`
	Address string `protobuf:"bytes,2,opt,name=address" json:"address,omitempty"`
}

func (m *Person_Email) Reset()                    { *m = Person_Email{} }
func (m *Person_Email) String() string            { return proto.CompactTextString(m) }
func (*Person_Email) ProtoMessage()               {}
func (*Person_Email) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 1} }

func (m *Person_Email) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *Person_Email) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func init() {
	proto.RegisterType((*Person)(nil), "person.Person")
	proto.RegisterType((*Person_Name)(nil), "person.Person.Name")
	proto.RegisterType((*Person_Email)(nil), "person.Person.Email")
}

func init() { proto.RegisterFile("src/person/person.v3.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 185 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2a, 0x2e, 0x4a, 0xd6,
	0x2f, 0x48, 0x2d, 0x2a, 0xce, 0xcf, 0x83, 0x52, 0x7a, 0x65, 0xc6, 0x7a, 0x05, 0x45, 0xf9, 0x25,
	0xf9, 0x42, 0x6c, 0x10, 0x01, 0xa5, 0x0b, 0x8c, 0x5c, 0x6c, 0x01, 0x60, 0xa6, 0x90, 0x3a, 0x17,
	0x4b, 0x5e, 0x62, 0x6e, 0xaa, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0xb7, 0x91, 0xb0, 0x1e, 0x54, 0x0b,
	0x44, 0x56, 0xcf, 0x2f, 0x31, 0x37, 0x35, 0x08, 0xac, 0x40, 0x48, 0x8b, 0x8b, 0x35, 0x35, 0x37,
	0x31, 0x33, 0x47, 0x82, 0x49, 0x81, 0x59, 0x83, 0xdb, 0x48, 0x04, 0x4d, 0xa5, 0x2b, 0x48, 0x2e,
	0x08, 0xa2, 0x44, 0xca, 0x8a, 0x8b, 0x05, 0xa4, 0x53, 0x48, 0x8c, 0x8b, 0x2d, 0x2d, 0x31, 0x37,
	0x33, 0xa7, 0x12, 0x6c, 0x3c, 0x67, 0x10, 0x94, 0x27, 0x24, 0xc5, 0xc5, 0x01, 0xd1, 0x9d, 0x08,
	0x32, 0x0e, 0x24, 0x03, 0xe7, 0x4b, 0x99, 0x72, 0xb1, 0x82, 0xcd, 0x12, 0x12, 0xe2, 0x62, 0xc9,
	0xce, 0xcc, 0x4b, 0x81, 0x6a, 0x05, 0xb3, 0x85, 0x24, 0xb8, 0xd8, 0x13, 0x53, 0x52, 0x8a, 0x52,
	0x8b, 0x8b, 0xa1, 0xfa, 0x60, 0xdc, 0x24, 0x36, 0xb0, 0x0f, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff,
	0xff, 0x39, 0x8d, 0xcf, 0xab, 0xff, 0x00, 0x00, 0x00,
}
